### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Nicasso** [bluem-development/bluem-php#10]
Hi,

I was a bit confused regarding the way this library is versioned. Recently there was a "major" update (https://github.com/DaanRijpkema/bluem-php/commit/bd8ce953f81b52cb843a9de923e74ba8bb4cc31d) from 2.0.x to 2.1.x containing some breaking changes. When breaking changes are introduced the versioning should have been updated to 3.0.x. Please try to use the semantic versioning standard (https://semver.org/) to prevent these sudden surprises when updating only a minor version.

Thanks in advance.
Nico

**Comment by petermeester** [comment]
Hi Nico,
Thanks for your message and tip for the semantic versioning standard. 
With the next releases, we will take it into account.
Peter
