### ISSUE TITLE
BIC is required for using iDEAL

### ISSUE THREAD

**Issue by bartbrouwer** [bluem-development/bluem-php#19]
When you create a payment without payment method, by default iDEAL is used without a BIC. That all works well.
When you set setPaymentMethodToIDEAL you have to define a BIC otherwise you'll get an validation error. 

Because Bluem works without defining a BIC (you'll get the bank selection screen) the expected behaviour is that setPaymentMethodToIDEAL can be called without a BIC.

**Comment by petermeester** [comment]
This has been changed.
