### ISSUE TITLE
DebtorReference is converted to alphanumeric only

### ISSUE THREAD

**Issue by bartbrouwer** [bluem-development/bluem-php#20]
In the Bluem API the DebtorReference has a restriction on the length (max 35) but not on the allowed characters.
The library is converting the DebtorReference to alphanumeric only while the API allowes whitespaces and special chars.

**Comment by DaanRijpkema** [comment]
This has been addressed in [the most recent release](https://github.com/bluem-development/bluem-php/releases/tag/2.1.4.1)
