### ISSUE TITLE
No possibility to provide a BrandId in PaymentTransactionRequest

### ISSUE THREAD

**Issue by bartbrouwer** [bluem-development/bluem-php#23]
Currently it is not possible to provide a BrandId in the  request to create a payment. As far as I see is it missing in all requests.
It should be part of RequestAttributes which is not implemented in any request.

**Comment by DaanRijpkema** [comment]
Hi Bart,
in the newest [release](https://github.com/bluem-development/bluem-php/releases/tag/2.1.4.0) you can set a brandID using the method 

```php
$brandID = "CompanyPayNL";
$request->setBrandID($brandID);
```
**Before** you perform the request.
This will allow you to enable payment methods without using the debtorWallet (a feature that will come in the future).
