### ISSUE TITLE
Version 2.3.2.4 breaks iban name check

### ISSUE THREAD

**Issue by jhhazelaar** [bluem-development/bluem-php#35]
The update to version 2.3.2.4 breaks the iban name check. The `IBANNameCheckBluemResponse` `GetNameResult` returns empty string.

We think that's because the `GetNameResult` calls `getKeyFromIBANCheckResult` with one parameter. And the second one is then `null`. The second one get's passed to the `getIBANCheckResultObject` as a parameter `$parentObjectKey`. This causes `$parent->{$parentObjectKey}` empty check to be true.

**Comment by DaanRijpkema** [comment]
Hi Jan Henk Hazelaar,
Thanks for your issue report. I think you are right. I can reproduce the issue and resolve it by adding the right keys to match the specific fields:
<img width="362" alt="image" src="https://github.com/bluem-development/bluem-php/assets/1172415/51305746-62bd-4cd0-b8e1-b3316a5bc084">

I've committed a fix for this [here](https://github.com/bluem-development/bluem-php/commit/db7fb48af2786e0b27de2790a148e54bfd095937). 
A minor release for this will follow shortly

**Comment by daanrijpkemacb** [comment]
Created release https://github.com/bluem-development/bluem-php/releases/tag/2.3.2.5
